*1.Write a python program to display all the header tags from Wikipedia.org*

In [1]:
import requests
from bs4 import BeautifulSoup

# Send a GET request to the Wikipedia homepage
url = 'https://www.wikipedia.org/'
response = requests.get(url)

# Parse the HTML code using BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')

# Find all header tags (h1 to h6) and print their text content
for header in soup.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6']):
    print(header.text.strip())

Wikipedia

The Free Encyclopedia
1 000 000+


articles
100 000+


articles
10 000+


articles
1 000+


articles
100+


articles

*2.Write a python program to display IMDB’s top rated 100 movies data (i.e name,rating ,year of release) and make data frame.*

In [4]:
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd


# Downloading imdb top 250 movie's data
url = 'http://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value')
		for b in soup.select('td.posterColumn span[name=ir]')]




# create a empty list for storing
# movie information
list = []

# Iterating over movies to extract
# each movie's details
for index in range(0, len(movies)):
	
	# Separating movie into: 'place',
	# 'title', 'year'
	movie_string = movies[index].get_text()
	movie = (' '.join(movie_string.split()).replace('.', ''))
	movie_title = movie[len(str(index))+1:-7]
	year = re.search('\((.*?)\)', movie_string).group(1)
	place = movie[:len(str(index))-(len(movie))]
	data = {"place": place,
			"movie_title": movie_title,
			"rating": ratings[index],
			"year": year,
			"star_cast": crew[index],
			}
	list.append(data)

# printing movie details with its rating.
for movie in list:
	print(movie['place'], '-', movie['movie_title'], '('+movie['year'] +
		') -', 'Starring:', movie['star_cast'], movie['rating'])


##.......##
df = pd.DataFrame(list)
df.to_csv('imdb_top_250_movies.csv',index=False)

1 - The Shawshank Redemption (1994) - Starring: Frank Darabont (dir.), Tim Robbins, Morgan Freeman 9.235791783449063
2 - The Godfather (1972) - Starring: Francis Ford Coppola (dir.), Marlon Brando, Al Pacino 9.155816482395851
3 - The Dark Knight (2008) - Starring: Christopher Nolan (dir.), Christian Bale, Heath Ledger 8.991768747400924
4 - The Godfather Part II (1974) - Starring: Francis Ford Coppola (dir.), Al Pacino, Robert De Niro 8.983840344272377
5 - 12 Angry Men (1957) - Starring: Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb 8.95319805207349
6 - Schindler's List (1993) - Starring: Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes 8.940208364249145
7 - The Lord of the Rings: The Return of the King (2003) - Starring: Peter Jackson (dir.), Elijah Wood, Viggo Mortensen 8.93255875847383
8 - Pulp Fiction (1994) - Starring: Quentin Tarantino (dir.), John Travolta, Uma Thurman 8.846164520155465
9 - The Lord of the Rings: The Fellowship of the Ring (2001) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.811083987057316
1 -  Il buono, il brutto, il cattivo (1966) - Starring: Sergio Leone (dir.), Clint Eastwood, Eli Wallach 8.788754933343673
11 - Forrest Gump (1994) - Starring: Robert Zemeckis (dir.), Tom Hanks, Robin Wright 8.766583247051605
12 - Fight Club (1999) - Starring: David Fincher (dir.), Brad Pitt, Edward Norton 8.747673372793662
13 - The Lord of the Rings: The Two Towers (2002) - Starring: Peter Jackson (dir.), Elijah Wood, Ian McKellen 8.736755392762072
14 - Inception (2010) - Starring: Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt 8.732643380951338
15 - The Empire Strikes Back (1980) - Starring: Irvin Kershner (dir.), Mark Hamill, Harrison Ford 8.6983403939877
16 - The Matrix (1999) - Starring: Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne 8.66913801715461
17 - GoodFellas (1990) - Starring: Martin Scorsese (dir.), Robert De Niro, Ray Liotta 8.653273706675023
18 - One Flew Over the Cuckoo's Nest (1975) - Starring: Milos Forman (dir.), Jack Nicholson, Louise Fletcher 8.637754706681594
19 - Se7en (1995) - Starring: David Fincher (dir.), Morgan Freeman, Brad Pitt 8.604628982111137
20 - Shichinin no samurai (1954) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura 8.597563291948388
21 - It's a Wonderful Life (1946) - Starring: Frank Capra (dir.), James Stewart, Donna Reed 8.597540955539166
22 - The Silence of the Lambs (1991) - Starring: Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins 8.588310136239185
23 - Saving Private Ryan (1998) - Starring: Steven Spielberg (dir.), Tom Hanks, Matt Damon 8.579797587261096
24 - Cidade de Deus (2002) - Starring: Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino 8.57931593291469
25 - Interstellar (2014) - Starring: Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway 8.572329854692128
26 - La vita è bella (1997) - Starring: Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi 8.5685796356717
27 - The Green Mile (1999) - Starring: Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan 8.563623585359153
28 - Star Wars (1977) - Starring: George Lucas (dir.), Mark Hamill, Harrison Ford 8.547666031503327
29 - Terminator 2: Judgment Day (1991) - Starring: James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton 8.538185513215199
30 - Back to the Future (1985) - Starring: Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd 8.517803354804043
31 - Sen to Chihiro no kamikakushi (2001) - Starring: Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette 8.515809490948802
32 - The Pianist (2002) - Starring: Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann 8.50776744932477
33 - Psycho (1960) - Starring: Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh 8.506191621210046
34 - Gisaengchung (2019) - Starring: Bong Joon Ho (dir.), Song Kang-ho, Lee Sun-kyun 8.500251454144859
35 - Léon (1994) - Starring: Luc Besson (dir.), Jean Reno, Gary Oldman 8.492523245452546
36 - The Lion King (1994) - Starring: Roger Allers (dir.), Matthew Broderick, Jeremy Irons 8.487769158025232
37 - Gladiator (2000) - Starring: Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix 8.487146884272839
38 - American History X (1998) - Starring: Tony Kaye (dir.), Edward Norton, Edward Furlong 8.481329135373896
39 - The Departed (2006) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon 8.476232974172415
40 - The Prestige (2006) - Starring: Christopher Nolan (dir.), Christian Bale, Hugh Jackman 8.469269912233035
41 - Whiplash (2014) - Starring: Damien Chazelle (dir.), Miles Teller, J.K. Simmons 8.46908318318249
42 - The Usual Suspects (1995) - Starring: Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne 8.468904495438082
43 - Casablanca (1942) - Starring: Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman 8.461230073478822
44 - Hotaru no haka (1988) - Starring: Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi 8.456470421600667
45 - Seppuku (1962) - Starring: Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama 8.45593584921791
46 - The Intouchables (2011) - Starring: Olivier Nakache (dir.), François Cluzet, Omar Sy 8.453204965984524
47 - Modern Times (1936) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.446614399165764
48 - Once Upon a Time in the West (1968) - Starring: Sergio Leone (dir.), Henry Fonda, Charles Bronson 8.44034847311742
49 - Nuovo Cinema Paradiso (1988) - Starring: Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale 8.43568090196556
50 - Rear Window (1954) - Starring: Alfred Hitchcock (dir.), James Stewart, Grace Kelly 8.43519875021764
51 - Alien (1979) - Starring: Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt 8.433234341150792
52 - City Lights (1931) - Starring: Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill 8.431967044465212
53 - Apocalypse Now (1979) - Starring: Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando 8.422675832704112
54 - Memento (2000) - Starring: Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss 8.418983684847209
55 - Django Unchained (2012) - Starring: Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz 8.40925557163502
56 - Raiders of the Lost Ark (1981) - Starring: Steven Spielberg (dir.), Harrison Ford, Karen Allen 8.405916555092784
57 - WALL·E (2008) - Starring: Andrew Stanton (dir.), Ben Burtt, Elissa Knight 8.395423333566985
58 - The Lives of Others (2006) - Starring: Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck 8.383642117957475
59 - Sunset Blvd (1950) - Starring: Billy Wilder (dir.), William Holden, Gloria Swanson 8.378787547207303
60 - Paths of Glory (1957) - Starring: Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker 8.37138505056525
61 - The Shining (1980) - Starring: Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall 8.364876699916714
62 - The Great Dictator (1940) - Starring: Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard 8.363806962512585
63 - Avengers: Infinity War (2018) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth 8.361903970224393
64 - Witness for the Prosecution (1957) - Starring: Billy Wilder (dir.), Tyrone Power, Marlene Dietrich 8.359981932645765
65 - Aliens (1986) - Starring: James Cameron (dir.), Sigourney Weaver, Michael Biehn 8.342971995040278
66 - Spider-Man: Into the Spider-Verse (2018) - Starring: Bob Persichetti (dir.), Shameik Moore, Jake Johnson 8.33856051402284
67 - American Beauty (1999) - Starring: Sam Mendes (dir.), Kevin Spacey, Annette Bening 8.329532529157703
68 - Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - Starring: Stanley Kubrick (dir.), Peter Sellers, George C. Scott 8.326961174096812
69 - The Dark Knight Rises (2012) - Starring: Christopher Nolan (dir.), Christian Bale, Tom Hardy 8.326016214717372
70 - Oldeuboi (2003) - Starring: Park Chan-wook (dir.), Choi Min-sik, Yoo Ji-tae 8.320017598413358
71 - Inglourious Basterds (2009) - Starring: Quentin Tarantino (dir.), Brad Pitt, Diane Kruger 8.318906516943459
72 - Amadeus (1984) - Starring: Milos Forman (dir.), F. Murray Abraham, Tom Hulce 8.316221139910299
73 - Coco (2017) - Starring: Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal 8.315191624142956
74 - Toy Story (1995) - Starring: John Lasseter (dir.), Tom Hanks, Tim Allen 8.314082052841794
75 - Braveheart (1995) - Starring: Mel Gibson (dir.), Mel Gibson, Sophie Marceau 8.31253272094528
76 - Joker (2019) - Starring: Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro 8.312517554255187
77 - Das Boot (1981) - Starring: Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer 8.311490187302203
78 - Avengers: Endgame (2019) - Starring: Anthony Russo (dir.), Robert Downey Jr., Chris Evans 8.303654459397666
79 - Mononoke-hime (1997) - Starring: Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida 8.30298804208058
80 - Once Upon a Time in America (1984) - Starring: Sergio Leone (dir.), Robert De Niro, James Woods 8.294393924242065
81 - Good Will Hunting (1997) - Starring: Gus Van Sant (dir.), Robin Williams, Matt Damon 8.293161097379404
82 - Kimi no na wa (2016) - Starring: Makoto Shinkai (dir.), Ryunosuke Kamiki, Mone Kamishiraishi 8.28300415982396
83 - Singin' in the Rain (1952) - Starring: Stanley Donen (dir.), Gene Kelly, Donald O'Connor 8.275307025812742
84 - 3 Idiots (2009) - Starring: Rajkumar Hirani (dir.), Aamir Khan, Madhavan 8.274770763012516
85 - Requiem for a Dream (2000) - Starring: Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto 8.273549357552602
86 - Tengoku to jigoku (1963) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada 8.272469334433781
87 - Toy Story 3 (2010) - Starring: Lee Unkrich (dir.), Tom Hanks, Tim Allen 8.270436148180437
88 - Capharnaüm (2018) - Starring: Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw 8.267106937787366
89 - Star Wars: Episode VI - Return of the Jedi (1983) - Starring: Richard Marquand (dir.), Mark Hamill, Harrison Ford 8.264057018856551
90 - Eternal Sunshine of the Spotless Mind (2004) - Starring: Michel Gondry (dir.), Jim Carrey, Kate Winslet 8.26151096624615
91 - 2001: A Space Odyssey (1968) - Starring: Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood 8.261441295054723
92 - Idi i smotri (1985) - Starring: Elem Klimov (dir.), Aleksey Kravchenko, Olga Mironova 8.259614655811022
93 - Reservoir Dogs (1992) - Starring: Quentin Tarantino (dir.), Harvey Keitel, Tim Roth 8.258455392721883
94 - Jagten (2012) - Starring: Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen 8.25741397290655
95 - Citizen Kane (1941) - Starring: Orson Welles (dir.), Orson Welles, Joseph Cotten 8.2495714720075
96 - M - Eine Stadt sucht einen Mörder (1931) - Starring: Fritz Lang (dir.), Peter Lorre, Ellen Widmann 8.249365914688319
97 - Lawrence of Arabia (1962) - Starring: David Lean (dir.), Peter O'Toole, Alec Guinness 8.249308840638538
98 - North by Northwest (1959) - Starring: Alfred Hitchcock (dir.), Cary Grant, Eva Marie Saint 8.245433656861007
99 - Ikiru (1952) - Starring: Akira Kurosawa (dir.), Takashi Shimura, Nobuo Kaneko 8.244625925017164
10 -  Vertigo (1958) - Starring: Alfred Hitchcock (dir.), James Stewart, Kim Novak 8.242554615641176
101 - The Apartment (1960) - Starring: Billy Wilder (dir.), Jack Lemmon, Shirley MacLaine 8.241689590784777
102 - Le fabuleux destin d'Amélie Poulain (2001) - Starring: Jean-Pierre Jeunet (dir.), Audrey Tautou, Mathieu Kassovitz 8.240825254429788
103 - A Clockwork Orange (1971) - Starring: Stanley Kubrick (dir.), Malcolm McDowell, Patrick Magee 8.237921417638105
104 - Double Indemnity (1944) - Starring: Billy Wilder (dir.), Fred MacMurray, Barbara Stanwyck 8.23786880727378
105 - Full Metal Jacket (1987) - Starring: Stanley Kubrick (dir.), Matthew Modine, R. Lee Ermey 8.236726416346317
106 - Scarface (1983) - Starring: Brian De Palma (dir.), Al Pacino, Michelle Pfeiffer 8.234842112274352
107 - Hamilton (2020) - Starring: Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo 8.23150110132588
108 - Incendies (2010) - Starring: Denis Villeneuve (dir.), Lubna Azabal, Mélissa Désormeaux-Poulin 8.227202125197039
109 - Heat (1995) - Starring: Michael Mann (dir.), Al Pacino, Robert De Niro 8.225934882914189
110 - To Kill a Mockingbird (1962) - Starring: Robert Mulligan (dir.), Gregory Peck, John Megna 8.225451570660834
111 - Up (2009) - Starring: Pete Docter (dir.), Edward Asner, Jordan Nagai 8.224782493697063
112 - The Sting (1973) - Starring: George Roy Hill (dir.), Paul Newman, Robert Redford 8.224555854680071
113 - Jodaeiye Nader az Simin (2011) - Starring: Asghar Farhadi (dir.), Payman Maadi, Leila Hatami 8.22123270087575
114 - Metropolis (1927) - Starring: Fritz Lang (dir.), Brigitte Helm, Alfred Abel 8.220735861853502
115 - Taxi Driver (1976) - Starring: Martin Scorsese (dir.), Robert De Niro, Jodie Foster 8.21873985263865
116 - LA Confidential (1997) - Starring: Curtis Hanson (dir.), Kevin Spacey, Russell Crowe 8.21827121552969
117 - Die Hard (1988) - Starring: John McTiernan (dir.), Bruce Willis, Alan Rickman 8.217608123737996
118 - Snatch (2000) - Starring: Guy Ritchie (dir.), Jason Statham, Brad Pitt 8.216701786866818
119 - Indiana Jones and the Last Crusade (1989) - Starring: Steven Spielberg (dir.), Harrison Ford, Sean Connery 8.21664228820209
120 - Ladri di biciclette (1948) - Starring: Vittorio De Sica (dir.), Lamberto Maggiorani, Enzo Staiola 8.215524246263554
121 - Top Gun: Maverick (2022) - Starring: Joseph Kosinski (dir.), Tom Cruise, Jennifer Connelly 8.214932773321992
122 - Taare Zameen Par (2007) - Starring: Aamir Khan (dir.), Darsheel Safary, Aamir Khan 8.212596364206739
123 - 1917 (2019) - Starring: Sam Mendes (dir.), Dean-Charles Chapman, George MacKay 8.211136617816495
124 - Der Untergang (2004) - Starring: Oliver Hirschbiegel (dir.), Bruno Ganz, Alexandra Maria Lara 8.203151707015
125 - Dangal (2016) - Starring: Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar 8.200106441281358
126 - Per qualche dollaro in più (1965) - Starring: Sergio Leone (dir.), Clint Eastwood, Lee Van Cleef 8.198888292482296
127 - Batman Begins (2005) - Starring: Christopher Nolan (dir.), Christian Bale, Michael Caine 8.197153931340534
128 - The Kid (1921) - Starring: Charles Chaplin (dir.), Charles Chaplin, Edna Purviance 8.190759723283984
129 - Some Like It Hot (1959) - Starring: Billy Wilder (dir.), Marilyn Monroe, Tony Curtis 8.190266462223486
130 - The Father (2020) - Starring: Florian Zeller (dir.), Anthony Hopkins, Olivia Colman 8.18200864161891
131 - All About Eve (1950) - Starring: Joseph L. Mankiewicz (dir.), Bette Davis, Anne Baxter 8.180239520424932
132 - The Wolf of Wall Street (2013) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Jonah Hill 8.178255715938747
133 - Green Book (2018) - Starring: Peter Farrelly (dir.), Viggo Mortensen, Mahershala Ali 8.17766682393405
134 - John Wick: Chapter 4 (2023) - Starring: Chad Stahelski (dir.), Keanu Reeves, Laurence Fishburne 8.174397762930829
135 - Judgment at Nuremberg (1961) - Starring: Stanley Kramer (dir.), Spencer Tracy, Burt Lancaster 8.17172921178817
136 - Ran (1985) - Starring: Akira Kurosawa (dir.), Tatsuya Nakadai, Akira Terao 8.164698656579066
137 - Casino (1995) - Starring: Martin Scorsese (dir.), Robert De Niro, Sharon Stone 8.164001042084822
138 - The Truman Show (1998) - Starring: Peter Weir (dir.), Jim Carrey, Ed Harris 8.161583105582075
139 - There Will Be Blood (2007) - Starring: Paul Thomas Anderson (dir.), Daniel Day-Lewis, Paul Dano 8.160736120052734
140 - Pan's Labyrinth (2006) - Starring: Guillermo del Toro (dir.), Ivana Baquero, Ariadna Gil 8.160260043260786
141 - Unforgiven (1992) - Starring: Clint Eastwood (dir.), Clint Eastwood, Gene Hackman 8.15843668204106
142 - The Sixth Sense (1999) - Starring: M. Night Shyamalan (dir.), Bruce Willis, Haley Joel Osment 8.154692859863621
143 - Shutter Island (2010) - Starring: Martin Scorsese (dir.), Leonardo DiCaprio, Emily Mortimer 8.153598133474828
144 - A Beautiful Mind (2001) - Starring: Ron Howard (dir.), Russell Crowe, Ed Harris 8.150761461419954
145 - Jurassic Park (1993) - Starring: Steven Spielberg (dir.), Sam Neill, Laura Dern 8.149645521171436
146 - Yôjinbô (1961) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Eijirô Tôno 8.147203965317516
147 - The Treasure of the Sierra Madre (1948) - Starring: John Huston (dir.), Humphrey Bogart, Walter Huston 8.146845737767023
148 - Monty Python and the Holy Grail (1975) - Starring: Terry Gilliam (dir.), Graham Chapman, John Cleese 8.145050024559923
149 - No Country for Old Men (2007) - Starring: Ethan Coen (dir.), Tommy Lee Jones, Javier Bardem 8.140350955440402
150 - The Great Escape (1963) - Starring: John Sturges (dir.), Steve McQueen, James Garner 8.139661475069783
151 - Kill Bill: Vol 1 (2003) - Starring: Quentin Tarantino (dir.), Uma Thurman, David Carradine 8.139083151039712
152 - Rashômon (1950) - Starring: Akira Kurosawa (dir.), Toshirô Mifune, Machiko Kyô 8.137533295869227
153 - The Thing (1982) - Starring: John Carpenter (dir.), Kurt Russell, Wilford Brimley 8.134091319320438
154 - Spider-Man: No Way Home (2021) - Starring: Jon Watts (dir.), Tom Holland, Zendaya 8.133918444475336
155 - Finding Nemo (2003) - Starring: Andrew Stanton (dir.), Albert Brooks, Ellen DeGeneres 8.131301415637811
156 - The Elephant Man (1980) - Starring: David Lynch (dir.), Anthony Hopkins, John Hurt 8.126866912990124
157 - Chinatown (1974) - Starring: Roman Polanski (dir.), Jack Nicholson, Faye Dunaway 8.12515464883815
158 - Raging Bull (1980) - Starring: Martin Scorsese (dir.), Robert De Niro, Cathy Moriarty 8.122583559891646
159 - V for Vendetta (2005) - Starring: James McTeigue (dir.), Hugo Weaving, Natalie Portman 8.122345892442079
160 - Gone with the Wind (1939) - Starring: Victor Fleming (dir.), Clark Gable, Vivien Leigh 8.121512398615812
161 - Lock, Stock and Two Smoking Barrels (1998) - Starring: Guy Ritchie (dir.), Jason Flemyng, Dexter Fletcher 8.119951532708818
162 - Dial M for Murder (1954) - Starring: Alfred Hitchcock (dir.), Ray Milland, Grace Kelly 8.119664900214932
163 - Inside Out (2015) - Starring: Pete Docter (dir.), Amy Poehler, Bill Hader 8.119618467947916
164 - El secreto de sus ojos (2009) - Starring: Juan José Campanella (dir.), Ricardo Darín, Soledad Villamil 8.117902030796653
165 - Hauru no ugoku shiro (2004) - Starring: Hayao Miyazaki (dir.), Chieko Baisho, Takuya Kimura 8.117552490671862
166 - Three Billboards Outside Ebbing, Missouri (2017) - Starring: Martin McDonagh (dir.), Frances McDormand, Woody Harrelson 8.111351502254093
167 - Trainspotting (1996) - Starring: Danny Boyle (dir.), Ewan McGregor, Ewen Bremner 8.110292724366431
168 - The Bridge on the River Kwai (1957) - Starring: David Lean (dir.), William Holden, Alec Guinness 8.110063491006583
169 - Prisoners (2013) - Starring: Denis Villeneuve (dir.), Hugh Jackman, Jake Gyllenhaal 8.106910732246787
170 - Warrior (2011) - Starring: Gavin O'Connor (dir.), Tom Hardy, Nick Nolte 8.102427483639794
171 - Fargo (1996) - Starring: Joel Coen (dir.), William H. Macy, Frances McDormand 8.102376560562618
172 - Gran Torino (2008) - Starring: Clint Eastwood (dir.), Clint Eastwood, Bee Vang 8.100149403584085
173 - Tonari no Totoro (1988) - Starring: Hayao Miyazaki (dir.), Hitoshi Takagi, Noriko Hidaka 8.09203440583386
174 - Catch Me If You Can (2002) - Starring: Steven Spielberg (dir.), Leonardo DiCaprio, Tom Hanks 8.091615773012014
175 - Million Dollar Baby (2004) - Starring: Clint Eastwood (dir.), Hilary Swank, Clint Eastwood 8.088545456888223
176 - Bacheha-Ye aseman (1997) - Starring: Majid Majidi (dir.), Mohammad Amir Naji, Amir Farrokh Hashemian 8.086409162343214
177 - Blade Runner (1982) - Starring: Ridley Scott (dir.), Harrison Ford, Rutger Hauer 8.084580351243055
178 - The Gold Rush (1925) - Starring: Charles Chaplin (dir.), Charles Chaplin, Mack Swain 8.084366441427486
179 - Klaus (2019) - Starring: Sergio Pablos (dir.), Jason Schwartzman, J.K. Simmons 8.08189511845769

*3.Write a python program to display list of respected former presidents of India (i.e. Name, Term of office) from https://presidentofindia.nic.in/former-presidents.htm*

In [20]:
import requests
from bs4 import BeautifulSoup

URL = "https://presidentofindia.nic.in/former-presidents.htm"
header = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}
page = requests.get(url=URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')
tables = soup.find_all("table")
for table in tables:
    if "cols-3" in table.get("class", []):
        rows = table.find_all('tr')[1:]
        for row in rows:
            columns = row.find_all('td')
            name = columns[0].text.strip()
            term = columns[1].text.strip()
            print(f'{name} - {term}')
        break
else:
    print("No table found with class 'cols-3'.")

Shri Ram Nath Kovind (birth - 1945)
Shri Pranab Mukherjee (1935-2020)
Smt Pratibha Devisingh Patil (birth - 1934)
DR. A.P.J. Abdul Kalam (1931-2015)
Shri K. R. Narayanan (1920 - 2005)
Dr Shankar Dayal Sharma (1918-1999)
Shri R Venkataraman (1910-2009)
Giani Zail Singh (1916-1994)
Shri Neelam Sanjiva Reddy (1913-1996)
Dr. Fakhruddin Ali Ahmed (1905-1977)
Shri Varahagiri Venkata Giri (1894-1980)
Dr. Zakir Husain (1897-1969)
Dr. Sarvepalli Radhakrishnan (1888-1975)
Dr. Rajendra Prasad (1884-1963)

*4. Write a python program to scrape cricket rankings from icc-cricket.com. You have to scrape:
    a) Top 10  ODI teams in men’s cricket along with the records for matches, points and rating
    b) Top 10 ODI Batsmen along with the records of their team and rating.
    c) Top 10 ODI bowlers along with the records of their team and rating*

In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

header = {'user-agent': "mozilla/5.0 (macintosh; intel mac os x 10_15_7) applewebkit/537.36 (khtml, like gecko) chrome/96.0.4664.110 safari/537.36"}
URL = ""
lst = []
names = []

choice = int(input("1. Men's Cricket ODI Rantings\n2. Top 10 ODI Batsmen Records\n3. Top 10 ODI Bowler's Records: "))

lst = []
if choice == 1:
    URL = "https://www.icc-cricket.com/rankings/mens/team-rankings/odi"
    names = ["Team", "Matches", "Points", "Rating"]
elif choice == 2:
    URL = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting"
    names = ["Player", "Team", "Rating", "Career Best Rating"]
elif choice == 3:
    URL = "https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling"
    names = ["Player", "Team", "Rating", "Career Best Rating"]
else:
    print("Invalid Input! Try Again")

page = requests.get(URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')
table = soup.find('table')
table_rows = table.find_all('tr')[1:]

for tr in table_rows[:10]:
    td = tr.find_all('td')
    row = [i.text.strip() for i in td if str(i)]
    lst.append(row)

for i in lst:
    try:
        i.pop(0)
    except IndexError:
        continue

df = pd.DataFrame(lst, columns=names)
df.to_csv('ICC.csv')
print(df)

                  Player Team Rating             Career Best Rating
0             Babar Azam  PAK    887  898 v West Indies, 10/06/2022
1  Rassie van der Dussen   SA    777      796 v England, 19/07/2022
2            Imam-ul-Haq  PAK    740  815 v West Indies, 12/06/2022
3        Quinton de Kock   SA    740    813 v Sri Lanka, 10/03/2019
4           Shubman Gill  IND    733    735 v Australia, 17/03/2023
5           David Warner  AUS    732     880 v Pakistan, 26/01/2017
6            Steve Smith  AUS    714     752 v Pakistan, 22/01/2017
7            Virat Kohli  IND    714      911 v England, 12/07/2018
8           Rohit Sharma  IND    704    885 v Sri Lanka, 06/07/2019
9        Kane Williamson   NZ    700        799 v India, 09/07/2019

*    5. Write a python program to scrape mentioned news details from https://www.cnbc.com/world/?region=world:
i)Headline
ii)Time
iii) News Link*

In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

URL = "https://www.cnbc.com/world/?region=world:"
header = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}

page = requests.get(URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')
lst = []

# Headline News
headline = soup.find("h2", class_="FeaturedCard-packagedCardTitle").find("a")
lst.append(["0 hours ago", headline.contents[0], headline['href']])

# Latest News
count = 1
latest_header = soup.find_all("div", class_="LatestNews-headlineWrapper")
for headings in latest_header:
    time = headings.find("time", "LatestNews-timestamp").contents[0]
    heading = headings.find('a')
    lst.append([time, heading.contents[0], heading['href']])

# Preprocessing
df = pd.DataFrame(lst, columns=["Time", "Article", "Link"])
drop_lst = []
count = 0
for i in df["Link"]:
    if i[0] != 'h':
        drop_lst.append(count)
    count += 1

new_df = df.drop(df.index[drop_lst])
new_df.to_csv('CNBC.csv', index=False)
print(new_df)

           Time                                            Article  \
0   0 hours ago  Saudi National Bank chair resigns just days af...
3    39 Min Ago  Binance, Changpeng Zhao broke compliance to at...
4    42 Min Ago  Supreme Court refuses appeal by lawyer jailed ...
5    52 Min Ago  Microsoft says its new version of Teams is twi...
6    59 Min Ago  Chipotle to pay ex-employees after closing Mai...
8    1 Hour Ago  The No. 1 thing women really want at work: 'It...
9    1 Hour Ago  Huawei reportedly says it has developed domest...
10   1 Hour Ago  Starlink rival OneWeb aims for global coverage...
12  2 Hours Ago  Here's why the U.S. had to sweeten terms to ge...
13  2 Hours Ago  How Walmart is using A.I. to make shopping bet...
14  2 Hours Ago  Apple CEO Tim Cook meets with China's commerce...
17  3 Hours Ago  Humza Yousaf wins leadership election of Scotl...
21  3 Hours Ago  First Republic rebounds by 13% on Monday to le...
22  4 Hours Ago  Stocks making the biggest moves premarket: Pin...
23  4 Hours Ago  Trump live updates: Grand jury set to resume a...
26  5 Hours Ago  5 things to know before the stock market opens...
29  7 Hours Ago             Treasury yields rise to start the week
30  7 Hours Ago  Netanyahu survives no-confidence vote as prote...

                                                 Link
0   https://www.cnbc.com/2023/03/27/saudi-national...
3   https://www.cnbc.com/2023/03/27/binance-and-fo...
4   https://www.cnbc.com/2023/03/27/supreme-court-...
5   https://www.cnbc.com/2023/03/27/microsoft-star...
6   https://www.cnbc.com/2023/03/27/chipotle-to-pa...
8   https://www.cnbc.com/2023/03/27/no-1-thing-wom...
9   https://www.cnbc.com/2023/03/27/huawei-says-it...
10  https://www.cnbc.com/2023/03/27/oneweb-aims-fo...
12  https://www.cnbc.com/2023/03/27/heres-why-the-...
13  https://www.cnbc.com/2023/03/27/how-walmart-is...
14  https://www.cnbc.com/2023/03/27/apple-ceo-tim-...
17  https://www.cnbc.com/2023/03/27/humza-yousaf-s...
21  https://www.cnbc.com/2023/03/27/first-republic...
22  https://www.cnbc.com/2023/03/27/stocks-making-...
23  https://www.cnbc.com/2023/03/27/trump-live-upd...
26  https://www.cnbc.com/2023/03/27/5-things-to-kn...
29  https://www.cnbc.com/2023/03/27/us-treasury-yi...
30  https://www.cnbc.com/2023/03/27/angry-protests...

*    6. Write a python program to scrape the details of most downloaded articles from AI in last 90 days https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles
Scrape below mentioned details:
    i) Paper Title
    ii) Authors
    iii) Published Date
    iv) Paper URL*

In [12]:
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime, timedelta

URL = "https://www.journals.elsevier.com/artificial-intelligence/most-cited-articles"
header = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}

page = requests.get(URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')

list_of_articles = soup.find('ul', class_="sc-9zxyh7-0 cMKaMj")
lst = []

# Define date range
today = datetime.today()
three_months_ago = (today - timedelta(days=90)).date()

for article in list_of_articles.find_all('li'):
    name = article.find('a')
    authors = article.find('span', 'sc-1w3fpd7-0 dnCnAO').contents[0]
    date = article.find('span', 'sc-1thf9ly-2 dvggWt').find('span').text
    
    # Convert date string to datetime object
    date_obj = datetime.strptime(date, '%d %B %Y')
    
    # Only add article to list if publication date is within last 90 days
    if date_obj.date() >= three_months_ago:
        link = name['href']
        lst.append([name.find('h2').contents[0],
                    authors,
                    date,
                    link])

df = pd.DataFrame(lst, columns=["Name", "Authors", "Date of Publication", "Link"])
df.to_csv('AICitedArticles.csv')
df.head(10)

,Name,Authors,Date of Publication,Link
0,Reward is enough,"Silver, David, Singh, Satinder, Precup, Doina,...",October 2021,https://www.sciencedirect.com/science/article/...
1,Making sense of raw input,"Evans, Richard, Bošnjak, Matko and 5 more",October 2021,https://www.sciencedirect.com/science/article/...
2,Law and logic: A review from an argumentation ...,"Prakken, Henry, Sartor, Giovanni",October 2015,https://www.sciencedirect.com/science/article/...
3,Creativity and artificial intelligence,"Boden, Margaret A.",August 1998,https://www.sciencedirect.com/science/article/...
4,Artificial cognition for social human–robot in...,"Lemaignan, Séverin, Warnier, Mathieu and 3 more",June 2017,https://www.sciencedirect.com/science/article/...
5,Explanation in artificial intelligence: Insigh...,"Miller, Tim",February 2019,https://www.sciencedirect.com/science/article/...
6,Making sense of sensory input,"Evans, Richard, Hernández-Orallo, José and 3 more",April 2021,https://www.sciencedirect.com/science/article/...
7,Conflict-based search for optimal multi-agent ...,"Sharon, Guni, Stern, Roni, Felner, Ariel, Stur...",February 2015,https://www.sciencedirect.com/science/article/...
8,Between MDPs and semi-MDPs: A framework for te...,"Sutton, Richard S., Precup, Doina, Singh, Sati...",August 1999,https://www.sciencedirect.com/science/article/...
9,The Hanabi challenge: A new frontier for AI re...,"Bard, Nolan, Foerster, Jakob N. and 13 more",March 2020,https://www.sciencedirect.com/science/article/...

*    7. Write a python program to scrape mentioned details from dineout.co.in
    i) Restaurant name
    ii) Cuisine
    iii) Location
    iv) Ratings
    v) ImageURL*

In [17]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

URL = "https://www.dineout.co.in/delhi-restaurants/buffet-special"
header = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}

page = requests.get(URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')

restaurant_list = soup.find_all('div', class_="restnt-card")

lst = []

for restaurant in restaurant_list:
    name = restaurant.find('div', class_='restnt-info cursor-pointer')
    cuisine = restaurant.find('div', class_='restnt-info-cusine ellipsis')
    location = restaurant.find('div', class_='restnt-info-ellipsis')
    ratings = restaurant.find('div', class_='restnt-rating rating-wrap right')
    image_url_elem = restaurant.find('img', class_='restnt-card-img')
    image_url = image_url_elem['src'] if image_url_elem is not None else ''
    lst.append([
        name.text.strip() if name is not None else '',
        cuisine.text.strip() if cuisine is not None else '',
        location.text.strip() if location is not None else '',
        ratings.text.strip() if ratings is not None else '',
        image_url,
    ])

df = pd.DataFrame(lst, columns=["Name", "Cuisine", "Location", "Ratings", "ImageURL"])
df.to_csv('DineoutRestaurants.csv')
df.head(10)

                                 Name                                 Cuisine  \
0  The Bier Library Brewery & Kitchen    Continental,Finger Food,North Indian
1                        Uru Brewpark  North Indian,Italian,Continental,Asian
2                      Hard Rock Cafe        Continental,American,Finger Food
3                  The Bangalore Cafe      Continental,North Indian,Fast Food
4                             Toscano                                 Italian
5                             Sanchez                                 Mexican
6                       Spice Terrace                    North Indian,Mughlai
7                          Biergarten                    Continental,European
8                         Cafe Azzure    Continental,Italian,Desserts,Bengali
9                           Cafe Noir                      Continental,French

                                            Location Ratings  \
0                        Koramangala,South Bangalore     4.4
1                           JP Nagar,South Bangalore     4.4
2                   St. Marks Road,Central Bangalore     4.4
3                     Shanti Nagar,Central Bangalore     4.3
4      UB City,,Vittal Mallya Road,Central Bangalore     4.5
5      UB City,,Vittal Mallya Road,Central Bangalore     4.3
6  JW Marriott Hotel,,Vittal Mallya Road,Central ...     4.2
7                        Koramangala,South Bangalore     4.4
8                          MG Road,Central Bangalore     4.3
9      UB City,,Vittal Mallya Road,Central Bangalore     4.4

                                           Image URL
0  https://im1.dineout.co.in/images/uploads/resta...
1  https://im1.dineout.co.in/images/uploads/resta...
2  https://im1.dineout.co.in/images/uploads/resta...
3  https://im1.dineout.co.in/images/uploads/resta...
4  https://im1.dineout.co.in/images/uploads/resta...
5  https://im1.dineout.co.in/images/uploads/resta...
6  https://im1.dineout.co.in/images/uploads/resta...
7  https://im1.dineout.co.in/images/uploads/resta...
8  https://im1.dineout.co.in/images/uploads/resta...
9  https://im1.dineout.co.in/images/uploads/resta...

*  8. Write a python program to scrape the details of top publications from Google Scholar from
https://scholar.google.com/citations?view_op=top_venues&h1=en
    i) Rank
    ii) Publication
    iii) h5-index
    iv) h5-median*

In [31]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

URL = "https://scholar.google.com/citations?view_op=top_venues&h1=en"
header = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"}

page = requests.get(URL, headers=header)
soup = BeautifulSoup(page.content, 'html.parser')

publication_list = soup.find_all('tr', class_ = "gsc_rsb_std")

lst = []

for publication in publication_list:
    rank = publication.find('td', class_='gsc_rsb_std gsc_rsb_sc1').text
    name = publication.find('td', class_='gsc_rsb_std gsc_rsb_sc2').text
    h5_index = publication.find('td', class_='gsc_rsb_std gsc_rsb_sc3').text
    h5_median = publication.find('td', class_='gsc_rsb_std gsc_rsb_sc4').text
    lst.append([rank, name, h5_index, h5_median])

df = pd.DataFrame(lst, columns=["Rank", "Publication", "h5-index", "h5-median"])
df.to_csv('GoogleScholarPublications.csv')
df.head(10)

Empty DataFrame
Columns: [Rank, Publication, h5-index, h5-median]
Index: []